<a href="https://colab.research.google.com/github/zeynep-tkn/PythonProjects/blob/main/NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Array: aynı veri tipinde N boyutlu dizi türüdür. Geleneksel listelere göre daha hızlı işlem yapmamızı sağlar.

In [1]:
data_list =[1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr=np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

In [7]:
data_list2=[[10,20,30],[40,50,60],[70,80,90]]

In [9]:
arr2=np.array(data_list2)

In [10]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
arr2[2,2]

90

In [12]:
np.arange(9,30,3)

array([ 9, 12, 15, 18, 21, 24, 27])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.eye(6)  #6 satır ve sütundan oluşan birim matris

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.randn(10,2)

array([[-0.57460603, -1.72011353],
       [ 0.38349576, -0.56661363],
       [ 1.54248129,  1.86796499],
       [ 0.82825801, -0.86267009],
       [-1.35424484, -0.76418877],
       [ 2.39507227, -0.40341578],
       [-1.62770635, -0.55506472],
       [ 0.49583513,  0.58068822],
       [ 0.05554083, -0.55808895],
       [ 1.02401763,  0.29440811]])


# Temel Operasyonlar

In [25]:
arr3=np.array([10,20,30,40,50])

In [26]:
arr4=np.array([2,3,4,5,6])

In [27]:
arr3

array([10, 20, 30, 40, 50])

In [28]:
arr4

array([2, 3, 4, 5, 6])

In [29]:
arr3 + arr4

array([12, 23, 34, 45, 56])

In [30]:
arr3 = arr3 **2

In [31]:
arr3

array([ 100,  400,  900, 1600, 2500])

In [32]:
np.sqrt(arr3)

array([10., 20., 30., 40., 50.])