<a href="https://colab.research.google.com/github/zeynep-tkn/PythonProjects/blob/main/NumpyArray2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array İndekslemesi ve Parçalanması

In [2]:
import numpy as np

In [3]:
liste = [i for i in range(1,10)]
liste

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
liste[1:5]

[2, 3, 4, 5]

In [5]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [7]:
boolValueArray = arr > 5
boolValueArray

array([False, False, False, False, False,  True,  True,  True,  True])

In [8]:
arr[boolValueArray] #doğru olanlar

array([6, 7, 8, 9])

In [9]:
arr[arr >5]

array([6, 7, 8, 9])